abundance_game/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page_view, name= "home"),
    path('game/', include('game.urls'), name = 'game'),
    path('accounts/', include('accounts.urls'), name = 'accounts'),
    path('confidence/', include('confidence.urls'), name= 'confidence'),
    path('books/', include('books.urls'), name='books')
    # a path to list of my professional goals
]

urlpatterns += staticfiles_urlpatterns()

game/urls.py
from django.urls import path
from . import views

app_name = 'game_root_name'

urlpatterns = [
    path('spend/', views.spend_view, name ='spend'),
    path('transaction/<int:id>', views.transaction_view, name = 'transaction'),
    path('game-day/<date>', views.game_day_view, name = 'game-day'),
    path('game-days/', views.game_day_list_view),
    path('', views.main_game_view, name='create'),
]

game/models.py
from django.db import models
from accounts.models import User



class Transaction(models.Model):
    amount = models.PositiveBigIntegerField()
    title = models.CharField(null = True, blank=True, max_length=64)
    description = models.TextField()
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(null=True, blank=True, auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name= "transaction")

    def __str__(self):
        return f"expence at:{self.date}, amount:{self.amount}"
        
    def show_title(self):
        return f"{self.title} : {self.amount}"

User.groups.related_name = 'userrelatedname'


class Game(models.Model):
    STATUS_CHOICES = (
        ("n", 'next_day'),
        ('l', 'lost')
    )

    day = models.SmallIntegerField(default=1)
    player = models.OneToOneField(User, on_delete=models.CASCADE, related_name='game')
    todays_amount = models.IntegerField(default=10000)
    game_status = models.CharField(max_length=5, choices=STATUS_CHOICES, default="n")

    def __str__(self):
        return self.player.username + "'s game"

game/forms.py
from django import forms
from . import models

class transaction_form(forms.ModelForm):
    class Meta:
        model = models.Transaction
        fields = ['title','amount', 'description']

game/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
import datetime
from game import forms
from . import forms
from django.contrib.auth.decorators import login_required
from .models import Transaction, Game

@login_required(login_url= '/accounts/login')
def spend_view(request):

    if not hasattr(request.user, 'game'):
        # print('fuck you')
        return redirect('game_root_name:create')


    # print(request.method)
    if request.method == "POST":
        form = forms.transaction_form(request.POST)
        # print('got_form\n')
        if form.is_valid():
            game = Game.objects.get(player = request.user)

            if form.cleaned_data['amount'] > game.todays_amount:
                return HttpResponse('sorry you will have more money tommorow :)')

            transaction = form.save(commit=False)
            transaction.owner = request.user
            transaction.save()

            game.todays_amount -= form.cleaned_data.get('amount')
            game.save()
            return redirect("game_root_name:game-day", str(datetime.date.today()))
        else:
            print("form errors:\n")
            # print(form.errors())

    form = forms.transaction_form()
    return render(request, 'spend.html', {'form':form})

@login_required(login_url= '/accounts/login')
def transaction_view(request, id):
    transaction = Transaction.objects.get(id = id)
    if request.user != transaction.owner:
        return HttpResponse("sorry! transaction not found")
    return HttpResponse(transaction.description)


@login_required(login_url= '/accounts/login')
def game_day_view(request, date):
    todays_transactions = Transaction.objects.filter(date = date, owner = request.user).order_by('-time')
    return render(request, 'todays_transactions.html', {"todays_transactions":todays_transactions})


@login_required(login_url= '/accounts/login')
def game_day_list_view(request):
    pass


@login_required(login_url= '/accounts/login')
def main_game_view(request):
    
    if hasattr(request.user, 'game'):
        return redirect('game_root_name:spend')
        
    user = request.user
    Game.objects.create(player = user)
    return redirect('game_root_name:spend')

game/templates/newgame.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>شروع بازی</title>
</head>
<body>
    <form action=""></form>
    
</body>
</html>

game/templates/spend.html
{% extends 'home.html' %}

{%block title%}
ثبت پرداخت
{% endblock %}

{% block content %}
<div class="spend-container">
    <form action="{% url 'game_root_name:spend' %}" method = "POST" class="spend-form">
        {% csrf_token %}
        عنوان {{form.title}}
        قابل پرداخت {{form.amount}}
        توضیحات {{form.description}}
        <input type="submit", value ="پرداخت" class="spend-submit">
    </form>
</div>
{% endblock%}   

game/templates/todays_transactions.html
{% extends 'home.html' %}

{% block title %}
خریدهای امروز
{% endblock %}


{% block content %}
    {% if todays_transactions %}
    <div class="transactions-list">
        {% for transaction in todays_transactions %}
        <div class="transaction">
            <a href="{% url 'game_root_name:transaction' id=transaction.id %}" style="color: white; text-decoration: none;">
                {{transaction.show_title}}
            </a>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="no-transaction">
        <p>امروز هیچ خریدی نداشتید</p>
        <p>برای ثبت خرید جدید رو دکمه پایین صفحه کلیک کنید</p>
    </div>
    {% endif %}
    <div class="empty">

    </div>
    <a href="../spend" class="new-spend">ثبت خرید جدید</a>
{% endblock%}