abundance_game/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page_view, name= "home"),
    path('game/', include('game.urls'), name = 'game'),
    path('accounts/', include('accounts.urls'), name = 'accounts'),
    path('confidence/', include('confidence.urls'), name= 'confidence'),
    path('books/', include('books.urls'), name='books')
    # a path to list of my professional goals
]

urlpatterns += staticfiles_urlpatterns()

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('add/', views.add_book_view, name= 'add'),
    path("delete/", views.delete_book_view, name='delete'),
    path('<str:status>/', views.read_books_view, name='change'),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game_root_name'

urlpatterns = [
    path('spend/', views.spend_view, name ='spend'),
    path('transaction/<int:id>', views.transaction_view, name = 'transaction'),
    path('game-day/<date>', views.game_day_view, name = 'game-day'),
    path('game-days/', views.game_day_list_view),
    path('', views.main_game_view, name='create'),
]

books/models.py
from django.db import models
from datetime import date
from accounts.models import User

class Book(models.Model):

    BOOK_STATUS = (
        ('r', 'read'),
        ('t', 'to_be_read'),
    )

    name = models.CharField(max_length=32)
    author = models.CharField(max_length=32)
    status = models.CharField(max_length=1, choices=BOOK_STATUS, default='t')
    target = models.DateField()
    times_read = models.SmallIntegerField(default=0)
    reader = models.ForeignKey(User, models.CASCADE, null=True, default=None)

    def __str__(self):
        return self.name
    
    def change_status(self):
        if self.status == 'r':
            self.status = 't'
        elif self.status == 't':
            self.status = 'r'
            self.times_read += 1
        self.save()
    
    def days_left(self):
        today = date.today()
        return (self.target - today).days
    
    def set_target(self,dateinput):
        self.target = dateinput
        self.save()

books/forms.py
from django.db.models import fields
from .models import Book
from django import forms

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author', 'target']
        

books/views.py
from tracemalloc import get_object_traceback
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from . import models
from .forms import BookForm, Book
from datetime import date

@login_required(login_url='../../accounts/login')
def read_books_view(request, status):
    if request.method == 'GET':
        books = models.Book.objects.filter(status = status, reader = request.user).order_by('target')
        if status == 'r':
            books =  models.Book.objects.filter(status = status, reader = request.user).order_by('times_read')
        today = date.today()
        var = {'books':books, 'today':today ,'state':status}
        return render(request, 'books.html', var)
    
    elif request.method == 'POST':
        book_id = request.POST.get('book_id')
        book = Book.objects.get(id = book_id)
        book.change_status()
        if request.POST.get('target'):
            date_in = request.POST['target'].split("T")[0].split('-')
            # print(date_in)
            book.set_target(date(int(date_in[0]),int(date_in[1]),int(date_in[2])))
            return redirect('../t')
        return redirect('../r')
    

@login_required(login_url= '../accounts/login')
def add_book_view(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.reader = request.user
            form.save()
            return redirect('../t')
        print('form is invalid\n')
    form = BookForm()
    return render(request, 'add_book.html', {'form':form})

@login_required(login_url='../accounts/login')
def delete_book_view(request):
    if request.method == 'POST':
        book = get_object_or_404(Book, id = request.POST.get('pk'))
        if book.reader == request.user:
            book.delete()
            return redirect("books:change" ,status = 't')
        else:
            return HttpResponse('!نمیتونی کتاب های بقیه رو حذف کنی')
    return HttpResponse('!صفحه مورد نظر پیدا نشد')

books/templates/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>کتاب های جدید</title>
</head>
<body>

{% extends 'home.html' %}

{% block title %}
کتاخانه دانشمندان
{% endblock %}


{% block content %}
<div class="spend-container">
    <form action="{% url 'books:add' %}" style="display: flex;flex-direction: column;" method="POST" class="spend-form">
        {% csrf_token %}
        نام کتاب {{form.name}}
        نام نویسنده {{form.author}}
        تاریخ هدف    
        (مثال : 02-02-2022)
        {{form.target}}
        <input type="submit" value="وارد کردن یه کتاب جدید">
    </form>
</div>
{% endblock%}

books/templates/books.html
{% extends 'home.html' %}

{% block title %}
کتاخانه دانشمندان
{% endblock %}


{% block content %}
{% for book in books %}
<div class="book-list transaction" >
    <h3>{{book.name}}</h3>
    <h4>{{book.author}}</h4>
    
    
    {% if book.status == 'r' %}
    {{book.times_read}}
    <form action="{% url 'books:change' status='t' %}" method="POST" class="again">
        {% csrf_token %}
        <input type="hidden" name="book_id" value={{book.id}}>
        <input type="datetime-local" name="target" required>
        <input type="submit" value="دوباره خواندن">
    </form>
    {% else %}
        روز فرصت داری {{book.days_left}} 
        <form action="{% url 'books:change' status='r' %}" method="POST" class="read-form">
            {% csrf_token %}
            <input type="hidden" name="book_id" value={{book.id}}>
            <input type="submit" value="خواندم" class="read-btn">
        </form>
    {% endif %}

    <form action="{% url 'books:delete'%}" class="delete-book" method="POST">
        {% csrf_token %}
        <input type="hidden" name="pk" value="{{book.id}}">
        <input type="submit" value="حذف" class="delete-book">
    </form>

</div>
{% endfor %}
{% if not books %}
<div class="no-book">
    <h1>کتابی وجود ندارد</h1>
    {% if state == 't'%}
        <a href=".././add/"><button>افزودن</button></a>
    {% endif %}
</div>
{% endif %} 

{% if state == 'r' %}
    <div class="empty">

    </div>
    <a href="../t" class="new-spend">مشاهده کتاب های خوانده نشده</a>
{% else %}
<div class="empty">

</div>
<a href="../r" class="new-spend">مشاهده کتاب های خوانده شده</a>
{% endif %}
{% endblock%}