abundance_game/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page_view, name= "home"),
    path('game/', include('game.urls'), name = 'game'),
    path('accounts/', include('accounts.urls'), name = 'accounts'),
    path('confidence/', include('confidence.urls'), name= 'confidence'),
    path('books/', include('books.urls'), name='books')
    # a path to list of my professional goals
]

urlpatterns += staticfiles_urlpatterns()

accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signin/", views.signin_view, name= "signin"),
    path("login/", views.login_view, name= "login"),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game_root_name'

urlpatterns = [
    path('spend/', views.spend_view, name ='spend'),
    path('transaction/<int:id>', views.transaction_view, name = 'transaction'),
    path('game-day/<date>', views.game_day_view, name = 'game-day'),
    path('game-days/', views.game_day_list_view),
    path('', views.main_game_view, name='create'),
]

accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    first_name = models.CharField(max_length=32)
    last_name = models.CharField(max_length=32)
    phone_number = models.CharField(max_length=11, null = True, blank=True)

    def __str__(self):
        return self.username

accounts/forms.py
from django import forms
from . import models

def all_numeric(pas):
    numbers = "123456789"
    count = 0
    for char in pas:
        if char in numbers:
            count += 1
    if count == len(pas):
        return True
    return False

class signin_form(forms.Form):
    first_name = forms.CharField(max_length=32, min_length=3)
    last_name = forms.CharField(max_length=32, min_length=3)
    username = forms.CharField(max_length=64, min_length=6)
    password1 = forms.CharField(max_length=32, min_length=8)
    password2 = forms.CharField(max_length=32, min_length=8)

    def clean_password(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password2 != password1:
            error = 'passwords didnt match'
            raise forms.ValidationError(error)
        elif all_numeric(password1):
            error = 'password is all numeric'
            raise forms.ValidationError(error)

    def save(self):
        user = models.User()
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['username']
        user.set_password(self.cleaned_data['password1'])
        user.save()
        return user

from .models import User

class login_form(forms.Form):
    username = forms.CharField(max_length = 64, min_length= 6)
    password = forms.CharField(max_length=32, min_length=8)

    def clean_username(self):
        if not User.objects.filter(username = self.cleaned_data['username']).exists():
            raise forms.ValidationError('user doesnot exist!')

    # def clean_password(self):
    #     if User.objects.filter(username = self.password).exists():
    #         if User.objects.get(username = self.password).password != self.cleaned_data['password']:
    #             raise forms.ValidationError("password is incorrect!")

accounts/views.py
from django.shortcuts import redirect, render
from . import forms
from django.contrib.auth import authenticate, login
from .models import User

def signin_view(request):
    if request.method == "POST":
        user = forms.signin_form(request.POST)
        if user.is_valid():
            user = user.save()
            login(request, user)
            if request.POST.get('next'):
                return redirect(request.POST.get('next'))
            return redirect("../../") # ----------------------------------------------------------------------------------

    form = forms.signin_form(request.POST)
    return render(request, 'signin.html', {"form":form})


def login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username = username, password = password)
        if user:
            login(request= request, user= user)
            return redirect('../../')
    form  = forms.login_form()
    return render(request, 'login.html', {'form':form})

accounts/templates/login.html
{% extends 'home.html' %}

{% block title %}
ورود
{% endblock %}


{% block content %}
    <div class="spend-container">
        <form action="{% url 'accounts:login' %}" method="POST" class="spend-form">
            {% csrf_token %}
            نام کاربری {{form.username}}
            رمز عبور {{form.password}}
            <p>حساب کاربری ندارید <a href="../signin" class = "signin-link">ثبت نام</a></p>
            <input type="submit" value="ورود">
        </form>
    </div>
{% endblock%}

accounts/templates/signin.html
{% extends 'home.html' %}

{% block title %}
ورود
{% endblock %}


{% block content %}
    <div class="spend-container">
        <form action="{% url 'accounts:signin' %}" method="POST" class="spend-form">
            <h3 class="note" style="color: red;">پر کردن همه فیلدها لازم است **</h3>
            {% csrf_token %}
            نام {{form.first_name}}
            نام خانوادگی {{form.last_name}}
            نام کاربری {{form.username}}
            رمز عبور {{form.password1}}
            تایید رمز عبور {{form.password2}}
            <p>حساب کاربری دارید <a href="../login" class = "signin-link">ورود</a></p>
            <input type="submit" value="ورود">
        </form>
    </div>
{% endblock%}