abundance_game/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'main'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home_page_view, name= "home"),
    path('game/', include('game.urls'), name = 'game'),
    path('accounts/', include('accounts.urls'), name = 'accounts'),
    path('confidence/', include('confidence.urls'), name= 'confidence'),
    path('books/', include('books.urls'), name='books')
    # a path to list of my professional goals
]

urlpatterns += staticfiles_urlpatterns()

books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('add/', views.add_book_view, name= 'add'),
    path("delete/", views.delete_book_view, name='delete'),
    path('<str:status>/', views.read_books_view, name='change'),
]

confidence/urls.py
from django.urls import path
from . import views

app_name = 'confidence'

urlpatterns = [
    path('add/', views.add_view, name='add'),
    path('list/', views.list_view, name='list'),
    path('todays-adds/', views.todays_adds_view),
]

game/urls.py
from django.urls import path
from . import views

app_name = 'game_root_name'

urlpatterns = [
    path('spend/', views.spend_view, name ='spend'),
    path('transaction/<int:id>', views.transaction_view, name = 'transaction'),
    path('game-day/<date>', views.game_day_view, name = 'game-day'),
    path('game-days/', views.game_day_list_view),
    path('', views.main_game_view, name='create'),
]

confidence/models.py
from django.db import models
from accounts.models import User

class GreateJob(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.CharField(max_length=128)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.owner.first_name} => {self.job[:30]}'

confidence/forms.py
from django import forms
from .models import GreateJob

class greate_job_form(forms.ModelForm):
    class Meta:
        model = GreateJob
        fields = ['job']

confidence/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from . import forms
from .models import GreateJob

@login_required(login_url='../../accounts/login')
def add_view(request):
    if request.method == 'POST':
        new_job = forms.greate_job_form(request.POST)
        if new_job.is_valid():
            new_job = new_job.save(commit=False)
            new_job.owner = request.user
            new_job.save()
            return redirect('confidence:list')
            # return HttpResponse('ثبت شد بابا خفن!')
    form = forms.greate_job_form()
    return render(request, 'add_job.html', {'form':form})

@login_required(login_url='../../accounts/login')
def list_view(request):
    jobs = GreateJob.objects.filter(owner = request.user).order_by('-id')
    jobs.reverse()
    return render(request, 'list_of_jobs.html', {'jobs':jobs, 'name':request.user})


@login_required(login_url='../../accounts/login')
def todays_adds_view(request):
    from datetime import date
    jobs = GreateJob.objects.filter(owner = request.user, date = date.today()).order_by('-date')
    jobs.reverse()
    return render(request, 'list_of_jobs.html', {'jobs':jobs, 'name':request.user})

confidence/templates/add_job.html
{% extends 'home.html' %}

{% block title %}
یه کار خفن دیگه
{% endblock %}

{% block content %}
<div class="spend-container">
    <form action="{% url 'confidence:add'%}" method="POST" class="spend-form">
        {% csrf_token %}
        یه کار خفن دیگه{{ form.job }}
        <input type="submit" value="ثبت خفنیها">
    </form>
</div>
{% endblock %}

confidence/templates/list_of_jobs.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}صفحه اصلی{% endblock %}</title>
</head>
<body>
        <header>
            <ul class="drills">
                <li><a href="{% url 'game_root_name:spend' %}">بازی فراوانی</a></li>
                <li><a href="{% url 'confidence:add' %}">اعتماد و عزت نفس</a></li>
                <li><a href="{% url 'books:change' status='r' %}">کتاب ها</a></li>
                <li><a href="#">اهداف</a></li>
            </ul>
            
        </header>
 
    {% block content %}
        <div class="transactions-list">
            {% for job in jobs %}
            <h2 style="color: #c08806; text-align: center;">{{job.job}}</h2>
            {% endfor %}
            {% if not jobs %}
            <h1 style="color: #c08806; text-align: center; margin-top: 80px;">هیچ موردی وجود ندارد</h1>
            {% endif %}
            <a href="../add/"><button class="spend-submit conf-btn">ثبت مورد جدید</button></a>
        </div>
    {% endblock %}
</body>
</html>